version: '3.9'

services:

  mongo:
    container_name: mongoAFO
    image: mongo
    restart: always
    ports:
      - 27017:27017

  app:
    build: .
    container_name: api
    ports:
      - 3000:3000
    volumes:
      - ./api:/usr/app
    depends_on:
      - mongo